---
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Root
  - package-ecosystem: "ruby"
    directory: "/"
    schedule:
      interval: "daily"
